### ISSUE TITLE
哈喽，AAAI23是结束了吗？代码整理工作咋样了

### ISSUE THREAD

**Issue by 464hee** [Vison307/PistoSeg#3]
首先恭喜你的论文选入AAAI23大会，其次您论文的想法我觉得新奇且具有一定潜力，非常期待相关在相关工作中引入你的思想，作为实验一个基线数据。看看是否有提升。

**Comment by Vison307** [comment]
不好意思，最近正在忙于撰写项目申请书；我们将尽快发布整理好的代码
