### ISSUE TITLE
对比实验请教

### ISSUE THREAD

**Issue by Key-lei** [Vison307/PistoSeg#4]
哈喽，这是一项非常有趣且有意义的工作，恭喜你们的论文在AAAI2023上发布！我注意到在论文的对比实验中你们使用了C-CAM 2022 CVPR的实验，目前我同样有工作需要和其对比但是数据集不同并且我在网上并没有找到相关的开源代码，请问你是如何得到这项实验结果的呢？

**Comment by Vison307** [comment]
Hello，感谢您对我们工作的关注。在论文准备期间我们是基于C-CAM CVPR论文中开源的代码链接进行实验的（ https://github.com/Tian-lab/C-CAM ），此时这个仓库还是公开的，或许您可以联系C-CAM的作者寻求相关帮助！
