### ISSUE TITLE
Where can I find Supplemental Materials of this paper?

### ISSUE THREAD

**Issue by lzaya** [Vison307/PistoSeg#7]
I have only found the 8 pages of the main text of this paper and could not locate the Supplemental Materials. Could you please share the link of the Supplemental Materials if it is available? Thank you very much!

**Comment by Vison307** [comment]
Thank you for your interest to our work! I have upload the supplementary pdf as 6106_AAAI23_supp.pdf in this repo!

**Comment by lzaya** [comment]
Thanks for your reply.
